#PBS -P <YOUR_PROJECT>
#PBS -l select=1:ncpus=4:ngpus=1:mem=32gb
#PBS -l walltime=0:10:00
#PBS -N job01

indir=/project/<YOUR_PROJECT>/path_to_photos/
outfile=job_out.json

module load singularity

cd $PBS_O_WORKDIR

singularity run --nv --bind /project:/project mega.img /bin/bash -c "python /build/cameratraps/detection/run_detector_batch.py /build/blobs/md_v5b.0.0.pt "${indir}" "${outfile}" --recursive --use_image_queue"
