#PBS -P <YOUR_PROJECT>
#PBS -l select=1:ncpus=4:ngpus=1:mem=32gb
#PBS -l walltime=0:10:00
#PBS -N job01

module load singularity

cd $PBS_O_WORKDIR

export SINGLUARITY_CACHEDIR=`pwd`
export SINGLUARITY_TMPDIR=`pwd`

singularity build scarches.img docker://nbutter/scarches:ubuntu1604

singularity run --nv --bind /project:/project scarches.img /bin/bash -c "cd "$PBS_O_WORKDIR" && python example_Unsupervised_surgery_pipeline_with_SCVI.py"
